parser: babel-eslint
extends:
  - airbnb
  - prettier
  - plugin:prettier/recommended
  - prettier/babel
  - prettier/react
plugins:
  - prettier
  - react
  - jsx-a11y
  - import
env:
  browser: true
  node: true
  es6: true
  jest: true
rules:
  prettier/prettier: error
  react/jsx-filename-extension: off
  react/prop-types:
    - error
    - ignore: [navigation]
  import/no-extraneous-dependencies: [error, { devDependencies: true }]
settings:
  import/resolver:
    node:
      moduleDirectory:
        # an array of absolute paths which will also be searched
        # think NODE_PATH
        - src
        - node_modules